# Generated by Django 3.2.3 on 2021-05-20 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mindcardapp', '0002_auto_20210519_2135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deck',
            old_name='user_id',
            new_name='user',
        ),
    ]
