# Generated by Django 3.2.3 on 2021-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindcardapp', '0003_rename_user_id_deck_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
