# Generated by Django 3.2.3 on 2021-05-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mindcardapp', '0004_card_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='name',
            field=models.CharField(max_length=280, unique=True),
        ),
    ]
