# Generated by Django 3.2.3 on 2021-06-24 16:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mindcardapp', '0005_alter_deck_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
